added config edit option in menu, changed sed command, more robust workflow, changed menu layout, error handling

diff --git a/d2launcher b/d2launcher
--- a/d2launcher
+++ b/d2launcher
@@ -8,55 +8,63 @@ script_dir=$(dirname "$script_file")
 script_id=$(basename "$script_file")
 script_config_file="$script_dir/$script_id.conf"
 script_res_dir="$script_dir/res"
-script_icon_file=$script_res_dir/icon.png
+script_icon_file="$script_res_dir/icon.png"
 script_help_file="$script_res_dir/d2launcher-help.html"
-
-desktop_file_name="Diablo II"
-desktop_file=$HOME/.local/share/applications/$script_id.desktop
 
 # Create config file
 if [ ! -f "$script_config_file" ]; then
-	zenity --info --width=250 --window-icon="$script_icon_file" --text="Please choose Diablo II binary dir..."
-	directory=$(zenity --file-selection --directory)
-	if [ "$directory" != "" ]; then
-		echo "d2_binary_dir=\"$directory\"" >> $script_config_file
-		echo "d2_exec=\"Diablo II.exe\"" >> $script_config_file
-		echo "d2_args=\"-3dfx -skiptobnet\"" >> $script_config_file		
-		echo "wine=\""'$script_res_dir'"/wine\"" >> $script_config_file
-		echo "wineprefix=\""'$script_dir'"/.wineprefix\"" >> $script_config_file
-	else
-		exit 1;
-	fi
+    echo "d2_binary_dir=\"\"" >> $script_config_file
+    echo "d2_exec=\"Diablo II.exe\"" >> $script_config_file
+    echo "d2_args=\"-3dfx\"" >> $script_config_file
 fi
 
 # Import config file
 . "$script_config_file"
 
+# Desktop file
+desktop_file_name="Diablo II"
+desktop_file="$HOME/.local/share/applications/$script_id.desktop"
+
+# Wine AppImage
+wine_url="https://github.com/ferion11/Proton_Appimage/releases/download/continuous/proton-linux-x86-v4.2-PlayOnLinux-x86_64.AppImage"
+wine="$script_res_dir/wine"
+wineprefix="$script_dir/.wineprefix"
+wine_user="steamuser"
+
+# Local res files
+d2_patch_res_file="$script_res_dir/d2-1.13c_files.zip"
+glide_res_file="$script_res_dir/gl32ogl14e.zip"
+
+# Patch files
 patch_files_dir="$script_res_dir/patches"
 patch_file_prefix="d2launcher-mxl"
 
-# Local res files
-d2_patch_data_file="$script_res_dir/d2-1.13c_files.zip"
-glide_data_file="$script_res_dir/gl32ogl14e.zip"
+# Diablo II
+d2_vid_test_exe="D2VidTst.exe"
+d2_glide_exe="glide-init.exe"
 
 # Median XL
 mxl_title="Median XL"
-mxl_version_url=http://get.median-xl.com/launcher/?get=versions
-mxl_dlls_url=http://get.median-xl.com/launcher/?get=dlls
-mxl_mod_url=http://get.median-xl.com/launcher/?get=mod
+mxl_version_url="http://get.median-xl.com/launcher/?get=versions"
+mxl_dlls_url="http://get.median-xl.com/launcher/?get=dlls"
+mxl_mod_url="http://get.median-xl.com/launcher/?get=mod"
 
-mxl_savegames_dir="$wineprefix/drive_c/users/steamuser/Application Data/MedianXL"
+mxl_savegames_dir="$wineprefix/drive_c/users/$wine_user/Application Data/MedianXL"
 mxl_savegames_prefix="$script_id-mxl-save"
 
 # D2 Stats
 d2_stats_url="https://github.com/Kyromyr/D2Stats/releases/download/3.11.0/D2Stats-3.11.0.rar"
-d2_stats_sigma_loader_url="https://github.com/SyndromeDayna/diablo-2-median-xl-sigma-loader/releases/latest/download/sigma-loader.exe"
-d2_stats_dir="$script_res_dir/d2-stats"
+d2_stats_res_dir="$script_res_dir/d2-stats"
+d2_stats_exe="D2Stats.exe"
+d2_sigma_loader_url="https://github.com/SyndromeDayna/diablo-2-median-xl-sigma-loader/releases/download/3/sigma-loader.exe"
+d2_sigma_loader_exe="sigma-loader.exe"
 
-# Wine AppImage url
-wine_url="https://github.com/ferion11/Proton_Appimage/releases/download/continuous/proton-linux-x86-v4.2-PlayOnLinux-x86_64.AppImage"
+log() {
+	echo "$(date "+%H:%M:%S") $script_id: $1"
+}
 
 send_notify() {
+    log "NOTIFY $1"
 	notify-send -i "$script_icon_file" "$script_title" "$1"
 }
 
@@ -66,7 +74,7 @@ if ! [ -x "$(command -v zenity)" ]; then
 	exit 1;
 fi
 if ! [ -x "$(command -v 7z)" ]; then
-	send_notify "7z not installed"
+	send_notify "p7zip not installed"
 	exit 1;
 fi
 if ! [ -x "$(command -v unrar)" ]; then
@@ -87,17 +95,74 @@ zenity() {
 }
 
 show_zenity_info() {
+    log "INFO $1"
 	zenity --info --text "$1"
 }
 
 show_zenity_error() {
+    log "ERROR $1"
 	zenity --error --text "$1"
+}
+
+check_d2_binary_dir() {
+    if [ ! -d "$d2_binary_dir" ]; then
+	    zenity --info --width=250 --text="Please choose Diablo II binary dir..."
+	    directory=$(zenity --file-selection --directory)
+	    if [ "$directory" != "" ]; then
+            replace_config_file_value "d2_binary_dir" "$directory"
+	    else
+		    exit 1;
+	    fi
+    fi
+}
+
+check_wine_standalone() {
+    if [ ! -f "$wine" ]; then
+        zenity --question --text="Wine Standalone is required. Download now?"
+        if [ $? == 1 ]; then
+            exit 0;
+        fi
+        (
+            install_wine
+            echo "# Wine standalone successfully downloaded"
+        ) | zenity --progress --text="Downloading Wine standalone" --auto-kill --pulsate
+    fi
+}
+
+install_wine() {
+    tmp_file="/tmp/wine.tmp"
+    curl -Lk $wine_url -o $tmp_file
+    mv $tmp_file $wine
+    chmod +x $wine
+}
+
+check_glide_installation() {
+    if [ ! -f "$d2_binary_dir/$d2_glide_exe" ]; then
+        zenity --question --text="Glide Wrapper not installed. Install now?"
+        if [ $? == 1 ]; then
+            exit 0;
+        fi
+        (
+	        install_glide
+            echo "# Glide wrapper successfully installed"
+        ) | zenity --progress --text="Installing Glide Wrapper" --auto-kill --pulsate
+    fi
+}
+
+install_glide() {
+	if [ ! -f "$glide_res_file" ]; then
+		zenity_error "$glide_res_file not found!"
+		exit 1;
+	fi
+    unzip -o "$glide_res_file" -d "$d2_binary_dir"
 }
 
 show_mxl_download_gui() {
 	# Parse mxl patch infos
-	latest_mxl_patch_json=$(curl "$mxl_version_url" -s | jq -r '.mod | [.[] ] | .[-1]')
-	latest_mxl_patch_version=$(echo "$latest_mxl_patch_json" | jq -r '.name' | cut -f3 -d" ")
+    latest_mxl_patch_json_file="/tmp/d2launcher_latest_mxl_patch.json"
+    ( curl "$mxl_version_url" -s | jq -r '.mod | [.[] ] | .[-1]' > $latest_mxl_patch_json_file )| zenity --progress --text="Fetching latest $mxl_title version info" --pulsate --auto-close
+
+	latest_mxl_patch_version=$(cat "$latest_mxl_patch_json_file" | jq -r '.name' | cut -f3 -d" ")
 	latest_mxl_patch_prefix="$patch_file_prefix-$latest_mxl_patch_version"
 
 	if [ "$latest_mxl_patch_version" = "" ]; then
@@ -149,9 +214,12 @@ show_mxl_patch_gui() {
 		show_zenity_error "No local $mxl_title patches found!\n\nDownload latest $mxl_title patch first."
 		exit 1;
 	fi
-
-	if [ ! -f "$d2_patch_data_file" ]; then
-		show_zenity_error "$d2_patch_data_file not found!"
+	if [ ! -f "$d2_patch_res_file" ]; then
+		show_zenity_error "$d2_patch_res_file not found!"
+		exit 1;
+	fi
+	if [ ! -f "$glide_res_file" ]; then
+		zenity_error "$glide_res_file not found!"
 		exit 1;
 	fi
 
@@ -166,8 +234,8 @@ show_mxl_patch_gui() {
             echo "# Patching glide ..."
             install_glide
 
-            echo "# Patching $d2_patch_data_file ..."
-            unzip -o "$d2_patch_data_file" -d "$d2_binary_dir"
+            echo "# Patching $d2_patch_res_file ..."
+            unzip -o "$d2_patch_res_file" -d "$d2_binary_dir"
 
             echo "# Patching $patch_file_result.zip ..."
             unzip -o "$patch_files_dir/$patch_file_result.zip" -d "$d2_binary_dir"
@@ -188,47 +256,47 @@ show_help_gui() {
 }
 
 exec_diablo() {
-	if [ ! -f "$d2_binary_dir/Diablo II.exe" ]; then
-		show_zenity_error "$d2_binary_dir/Diablo II.exe not found"
+	if [ ! -f "$d2_binary_dir/$d2_exec" ]; then
+		show_zenity_error "$d2_binary_dir/$d2_exec not found"
 		exit 1;
 	fi
 
-	install_glide
-
-	cd "$d2_binary_dir"
-	env WINEPREFIX="$wineprefix" $wine start /unix "$d2_exec" "$d2_args"
+    if pgrep -x "$d2_stats_exe" >/dev/null; then
+	    env WINEPREFIX="$wineprefix" "$wine" start /unix "$d2_binary_dir/$d2_sigma_loader_exe" "$d2_args"
+    else
+	    env WINEPREFIX="$wineprefix" "$wine" start /unix "$d2_binary_dir/$d2_exec" "$d2_args"
+    fi
 }
 
 exec_d2_stats() {
-    if [ ! -f "$d2_stats_dir/D2Stats.exe" ]; then
+    if [ ! -f "$d2_stats_res_dir/$d2_stats_exe" ]; then
         zenity --question --text="D2Stats is required. Download now?"
         if [ $? == 1 ]; then
             exit 0;
         fi
         (
-            mkdir -p "$d2_stats_dir"
-            cd "$d2_stats_dir"
+            mkdir -p "$d2_stats_res_dir"
+            cd "$d2_stats_res_dir"
             rar_file=d2-stats.rar
             curl -Lk $d2_stats_url -o $rar_file
             unrar x $rar_file
             rm $rar_file
-            echo "# D2-Stats successfully downloaded"
-        ) | zenity --progress --text="Downloading D2-Stats" --auto-kill --pulsate
+            echo "# D2Stats successfully downloaded"
+        ) | zenity --progress --text="Downloading D2Stats" --auto-kill --pulsate
     fi
     
-    if [ ! -f "$d2_binary_dir/sigma-loader.exe" ]; then
-        zenity --question --text="sigma-loader.exe is required. Download now?"
+    if [ ! -f "$d2_binary_dir/$d2_sigma_loader_exe" ]; then
+        zenity --question --text="$d2_sigma_loader_exe is required. Download now?"
         if [ $? == 1 ]; then
             exit 0;
         fi
         (
-            curl -Lk $d2_stats_sigma_loader_url -o "$d2_binary_dir/sigma-loader.exe"
-            replace_config_file_value "d2_exec" "\"sigma-loader.exe\""
-            echo "# sigma-loader.exe successfully downloaded"
-        ) | zenity --progress --text="Downloading sigma-loader.exe" --auto-kill --pulsate
+            curl -Lk $d2_sigma_loader_url -o "$d2_binary_dir/$d2_sigma_loader_exe"
+            echo "# $d2_sigma_loader_exe successfully downloaded"
+        ) | zenity --progress --text="Downloading $d2_sigma_loader_exe" --auto-kill --pulsate
     fi
 
-	env WINEPREFIX="$wineprefix" $wine start /unix "$d2_stats_dir/D2Stats.exe"
+	env WINEPREFIX="$wineprefix" $wine start /unix "$d2_stats_res_dir/$d2_stats_exe"
 	
 	# Workaround for disabling D2 Stats system tray
 	for i in 1 2 3 4 5; do
@@ -243,24 +311,34 @@ exec_d2_stats() {
 }
 
 exec_d2_video_settings() {
-	if [ ! -f "$d2_binary_dir/D2VidTst.exe" ]; then
-		show_zenity_error "$d2_binary_dir/D2VidTst.exe not found"
+	if [ ! -f "$d2_binary_dir/$d2_vid_test_exe" ]; then
+		show_zenity_error "$d2_binary_dir/$d2_vid_test_exe not found"
 		exit 1;
 	fi
-	cd "$d2_binary_dir"
-	env WINEPREFIX="$wineprefix" $wine start /unix "D2VidTst.exe"
+	env WINEPREFIX="$wineprefix" $wine start /unix "$d2_binary_dir/$d2_vid_test_exe"
 }
 
 exec_glide_settings() {
-    install_glide
-    cd "$d2_binary_dir"
-    env WINEPREFIX="$wineprefix" $wine start /unix "glide-init.exe"
+    check_glide_installation
+    env WINEPREFIX="$wineprefix" $wine start /unix "$d2_binary_dir/$d2_glide_exe"
+}
+
+show_edit_config() {
+    result=$(zenity --text-info --height=250 --width=500 --ok-label="Save" --cancel-label="Cancel" --editable --filename="$script_config_file")
+    if [ $? = 0 ]; then
+        echo "$result" > $script_config_file
+        send_notify "$script_config_file saved"
+    fi
 }
 
 exec_export_data() {
+    if [ ! -d "$mxl_savegames_dir" ]; then
+	    show_zenity_error "$mxl_savegames_dir not found"
+		exit 1;   
+    fi
 	directory=$(zenity --file-selection --directory)
 	if [ "$directory" != "" ]; then
-		filename="$mxl_savegames_prefix-$(date "+%Y%m%d%H%M").zip"
+		filename="$mxl_savegames_prefix-$(date "+%Y-%m-%d-%H%M").zip"
 		cd "$mxl_savegames_dir"
 		zip -r -0 "$directory/$filename" .
 		show_zenity_info "Data successfully exported: $directory/$filename"
@@ -276,23 +354,11 @@ exec_import_data() {
 	fi
 }
 
-install_glide() {
-	if [ ! -f "$d2_binary_dir/glide-init.exe" ]; then
-		if [ ! -f "$glide_data_file" ]; then
-			zenity_error "$glide_data_file not found!"
-			exit 1;
-		fi
-	    unzip -o "$glide_data_file" -d "$d2_binary_dir"
-	    send_notify "Glide wrapper was installed"
-	fi
-}
-
 replace_config_file_value() {
     key=$1
     value=$2
-    # Maybe -c is needed
-    sed -i "s/\($key *= *\).*/\1$value/" $script_config_file
-    send_notify "$key was changed to $value in $script_config_file"
+    sed -i "s#$key=.*#$key=\"$value\"#g" $script_config_file
+    send_notify "$key was set to $value"
 }
 
 create_desktop_file() {
@@ -311,23 +377,10 @@ remove_desktop_file() {
 	show_zenity_info "$desktop_file successfully removed"
 }
 
-# Check for wine standalone
-if [ ! -f "$wine" ]; then
-    zenity --question --text="Wine Standalone is required. Download now?"
-    if [ $? == 1 ]; then
-        exit 0;
-    fi
-    (
-        tmp_file="/tmp/wine.tmp"
-        curl -Lk $wine_url -o $tmp_file
-        mv $tmp_file $wine
-        chmod +x $wine
-        echo "# Wine standalone successfully downloaded"
-    ) | zenity --progress --text="Downloading Wine standalone" --auto-kill --pulsate
-fi
-
 # Main
 while(true); do
+
+    check_d2_binary_dir
 
     # Refresh config file
     . "$script_config_file"
@@ -339,62 +392,71 @@ while(true); do
 		mxl_status="Installed $mxl_title version: "$(cat $d2_xml_version_file)
 	fi
 
-	item_01="Start Diablo II"
-	item_02="Download latest $mxl_title patch"
-	item_03="Install local $mxl_title patch"
-	item_04="Open D2 Stats"
-	item_05="Open D2 Video Settings"
-	item_06="Open Glide Settings"
-	item_07="Import $mxl_title Savegames"
-	item_08="Export $mxl_title Savegames"
-
+	item_01="Diablo II"
+	item_02="D2 Stats"
+	item_03="Glide Settings"
+	item_04="D2 Video Settings"
+	item_05="Edit Config"
+	item_06="Download $mxl_title"
+	item_07="Install $mxl_title"
+	item_08="Import Savegames"
+	item_09="Export Savegames"
 	if [ ! -f $desktop_file ]; then
-		item_09="Create Menu Entry"
+		item_10="Create Icon"
 	else
-		item_09="Remove Menu Entry"
+		item_10="Remove Icon"
 	fi
-	item_10="Help"
+	item_11="Help"
 
     # Show menu
-    result=$(zenity --list --radiolist --height=350 --ok-label="Ok" --cancel-label="Exit" --text="$mxl_status\n" --hide-header --column="" --column="" TRUE "$item_01" FALSE "$item_02" FALSE "$item_03" FALSE "$item_04" FALSE "$item_05" FALSE "$item_06" FALSE "$item_07" FALSE "$item_08" FALSE "$item_09" FALSE "$item_10")
+    result=$(zenity --list --radiolist --height=350 --ok-label="Ok" --cancel-label="Exit" --text="$mxl_status\n" --hide-header --column="" --column="" TRUE "$item_01" FALSE "$item_02" FALSE "$item_03" FALSE "$item_04" FALSE "$item_05" FALSE "$item_06" FALSE "$item_07" FALSE "$item_08" FALSE "$item_09" FALSE "$item_10" FALSE "$item_11")
 
     # If user exit
     if [ $? = 1 ]; then
         break; exit 0;
     fi
     if [ "$result" = "$item_01" ]; then
+        check_wine_standalone
+        check_glide_installation
         exec_diablo
         exit 0;
     fi
     if [ "$result" = "$item_02" ]; then
-        show_mxl_download_gui
-    fi
-    if [ "$result" = "$item_03" ]; then
-        show_mxl_patch_gui
-    fi
-    if [ "$result" = "$item_04" ]; then
+        check_wine_standalone
         exec_d2_stats
     fi
-    if [ "$result" = "$item_05" ]; then
-        exec_d2_video_settings
-    fi
-    if [ "$result" = "$item_06" ]; then
+    if [ "$result" = "$item_03" ]; then
+        check_wine_standalone
+        check_glide_installation
         exec_glide_settings
     fi
+    if [ "$result" = "$item_04" ]; then
+        check_wine_standalone
+        exec_d2_video_settings
+    fi
+    if [ "$result" = "$item_05" ]; then
+        show_edit_config
+    fi
+    if [ "$result" = "$item_06" ]; then
+        show_mxl_download_gui
+    fi
     if [ "$result" = "$item_07" ]; then
-        exec_import_data
+        show_mxl_patch_gui
     fi
     if [ "$result" = "$item_08" ]; then
-        exec_export_data
+        exec_import_data
     fi
     if [ "$result" = "$item_09" ]; then
+        exec_export_data
+    fi
+    if [ "$result" = "$item_10" ]; then
         if [ ! -f "$desktop_file" ]; then
             create_desktop_file
         else
             remove_desktop_file
         fi
     fi
-    if [ "$result" = "$item_10" ]; then
+    if [ "$result" = "$item_11" ]; then
         show_help_gui
     fi
 done
